-- ============================================================
--  V1 — Baslangic semasi.
--
--  Bu dosya, Hibernate'in ddl-auto=create-drop ile o ana kadar
--  otomatik urettigi semanin (tablo/kolon/FK) elle yazilmis, kalici
--  hali. Bundan sonra sema degisikligi SADECE yeni bir Vn__aciklama.sql
--  dosyasiyla yapilir — asla bu dosya elle degistirilmez (Flyway zaten
--  uygulanmis bir migration'in checksum'i degisirse hata verir).
--
--  price alani double DEGIL numeric(10,2): para kayan noktali sayiyla
--  tutulmaz (bkz. ServiceItem.java'daki aciklama).
-- ============================================================

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    sur_name   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    phone      VARCHAR(255) NOT NULL,
    role       VARCHAR(255) NOT NULL CHECK (role IN ('USER', 'BUSINESS_OWNER', 'ADMIN'))
);

CREATE TABLE businesses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    address      VARCHAR(255) NOT NULL,
    phone        VARCHAR(255),
    description  VARCHAR(255),
    owner_id     BIGINT NOT NULL,
    open_time    TIME(0),
    close_time   TIME(0),
    category     VARCHAR(255) NOT NULL CHECK (category IN
                     ('HAIRDRESSER', 'BARBER', 'BEAUTY_SALON', 'SPA_WELLNESS',
                      'NAIL_STUDIO', 'MAKEUP_STUDIO', 'TATTOO_STUDIO')),
    CONSTRAINT fk_businesses_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE service_items (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(255) NOT NULL,
    description            VARCHAR(255) NOT NULL,
    price                  NUMERIC(10, 2) NOT NULL,
    duration_in_minutes    INTEGER NOT NULL,
    business_id            BIGINT NOT NULL,
    is_active              BOOLEAN NOT NULL,
    CONSTRAINT fk_service_items_business FOREIGN KEY (business_id) REFERENCES businesses (id)
);

CREATE TABLE appointments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_date  TIMESTAMP(6) NOT NULL,
    -- NOT: Faz 2.1'de COMPLETED/NO_SHOW durumlarindan NO_SHOW eklendiginde
    -- bu CHECK'in bir migration'la (V2) genisletilmesi gerekecek.
    status            VARCHAR(255) NOT NULL CHECK (status IN
                          ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED')),
    customer_id       BIGINT NOT NULL,
    business_id       BIGINT NOT NULL,
    service_id        BIGINT NOT NULL,
    CONSTRAINT fk_appointments_customer FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT fk_appointments_business FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT fk_appointments_service FOREIGN KEY (service_id) REFERENCES service_items (id)
);

-- Postgres, FK sutunlarina otomatik index KOYMAZ (sadece referans verilen
-- PK tarafi indexlenir) -- business_id/category uzerinden filtreleme
-- sorgulari (getBusinessAppointments, getBusinessesByCategory vb.) index
-- olmadan sequential scan yapardi.
CREATE INDEX idx_appointments_business_date ON appointments (business_id, appointment_date);
CREATE INDEX idx_businesses_category ON businesses (category);

-- Yarış koşulu korumasi (bkz. ROADMAP K9 / AppointmentService.createAppointment
-- ustundeki aciklama). KISMI (partial) index: sadece PENDING/APPROVED
-- durumundaki randevular "o saati isgal etmis" sayilir -- REJECTED/CANCELLED
-- bir randevu ayni saate yeniden randevu alinmasini ENGELLEMEMELI. Duz bir
-- UNIQUE(business_id, appointment_date) bunu ifade edemezdi, WHERE kosulu
-- gerekiyordu. Eskiden bu index uygulama aciliminda elle (AppointmentSlotIndexInitializer
-- adli bir CommandLineRunner ile) kuruluyordu -- Flyway geldigine gore o
-- gecici cozum kaldirildi, index artik burada, semanin resmi bir parcasi.
CREATE UNIQUE INDEX ux_appointments_active_slot ON appointments (business_id, appointment_date)
    WHERE status IN ('PENDING', 'APPROVED');
