-- ============================================================
--  V2 — Haftalık çalışma saatleri ve özel kapanış günleri.
--
--  Business.open_time/close_time hala duruyor (geriye dönük uyumluluk,
--  bkz. WorkingHour.java'daki açıklama) — bu iki yeni tablo ONLARI
--  DEĞİŞTİRMİYOR, üzerine ek bir katman olarak çalışıyor. Bir işletme
--  için working_hours satırı varsa AvailabilityCalculator onu kullanır,
--  yoksa businesses.open_time/close_time'a düşer.
-- ============================================================

CREATE TABLE working_hours (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id  BIGINT NOT NULL,
    day_of_week  VARCHAR(20) NOT NULL CHECK (day_of_week IN
                     ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    open_time    TIME(0),
    close_time   TIME(0),
    is_closed    BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_working_hours_business FOREIGN KEY (business_id) REFERENCES businesses (id),
    -- Ayni isletme + ayni gun icin iki satir olamaz (WorkingHourService'teki
    -- upsert mantiginin veritabani seviyesindeki garantisi).
    CONSTRAINT uq_working_hours_business_day UNIQUE (business_id, day_of_week)
);

CREATE TABLE business_closures (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT NOT NULL,
    closure_date  DATE NOT NULL,
    reason        VARCHAR(255),
    CONSTRAINT fk_business_closures_business FOREIGN KEY (business_id) REFERENCES businesses (id),
    -- Ayni tarih icin ayni isletmede iki kapanis kaydi olamaz.
    CONSTRAINT uq_business_closures_business_date UNIQUE (business_id, closure_date)
);
