-- ============================================================
--  V4 — Faz 2.3: personel (Staff) veri modeli.
--
--  Bu adim randevu akisina henuz baglanmiyor -- appointments tablosuna
--  staff_id Faz 2.5'te eklenecek. Su an sadece isletme sahibinin personel
--  listesini, kimin hangi hizmeti verdigini ve personel bazli calisma
--  saatlerini yonetebilmesi icin.
-- ============================================================

CREATE TABLE staff (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id  BIGINT NOT NULL,
    name         VARCHAR(255) NOT NULL,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_staff_business FOREIGN KEY (business_id) REFERENCES businesses (id)
);

-- FK sutunlarina Postgres otomatik index koymuyor (bkz. V1'deki ayni not) --
-- getStaffByBusiness sorgusu bu olmadan sequential scan yapardi.
CREATE INDEX idx_staff_business ON staff (business_id);

-- Bir personelin verebildigi hizmetler (many-to-many baglanti tablosu).
CREATE TABLE staff_services (
    staff_id    BIGINT NOT NULL,
    service_id  BIGINT NOT NULL,
    PRIMARY KEY (staff_id, service_id),
    CONSTRAINT fk_staff_services_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_staff_services_service FOREIGN KEY (service_id) REFERENCES service_items (id)
);

-- WorkingHour/business_closures ile ayni tasarim (bkz. V2), personel bazli
-- hali.
CREATE TABLE staff_working_hours (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id     BIGINT NOT NULL,
    day_of_week  VARCHAR(20) NOT NULL CHECK (day_of_week IN
                     ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    open_time    TIME(0),
    close_time   TIME(0),
    is_closed    BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_staff_working_hours_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT uq_staff_working_hours_staff_day UNIQUE (staff_id, day_of_week)
);
