-- ============================================================
--  V6 — Faz 2.6: Review entity, "sadece gitmiş kişi yorum yapar"
--  garantisinin şema katmanı.
--
--  appointment_id UNIQUE: bir randevuya en fazla bir yorum yazılabilir,
--  ve yorum SADECE var olan bir randevuya (FK) bağlanabilir -- randevusu
--  olmayan biri, uygulama kodu ne yaparsa yapsın, satır ekleyemez.
--  rating CHECK ile 1-5 aralığına sabitlendi (servis katmanındaki
--  @Min/@Max Bean Validation'ın veritabanı seviyesindeki yedeği).
-- ============================================================

CREATE TABLE reviews (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL UNIQUE,
    rating         INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment        VARCHAR(1000),
    created_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_reviews_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id)
);
