spring.application.name=backend
server.port=8080

# H2 Veritabanı Ayarları
spring.datasource.url=jdbc:h2:mem:randevum_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Konsolu (Tarayıcıdan Veritabanını Görmek İçin)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect


spring.output.ansi.enabled=ALWAYS